spawn:
  location:
  - world|0.0|70.0|0.0|0.0|0.0
show-join-message: true
join-message: "&5Welcome %u to the server!"
allow-bed-spawn: true
many-spawn: false
check-bed-radius: false
bed-radius: 15.0
clear-bed-spawn: true
radial-spawning: false
spawn-radius: 150.0
use-primary-spawn: true
