name: NerdSpawn
main: nu.nerd.nerdspawn.NerdSpawn
version: ${project.version}
description: ${project.description}
website: ${project.url}
author: Travis Watkins

commands:
  spawn:
    description: Teleports you to the spawn location.
    usage: |
           Usage: /<command> - Teleport to spawn.
  setspawn:
    description: Sets the spawn location.
    usage: |
           Usage: /<command> - Sets spawn location.
  nerdspawn:
    description: Sets the spawn location
    usage: |
           Usage: /<command> reload - Reload configuration.           
           Usage: /<command> list - List spawns.           

permissions:
  nerdspawn.*:
    description: Allow the use of all commands.
    children:
    - nerdspawn.spawn
    - nerdspawn.setspawn
    - nerdspawn.reload
    - nerdspawn.list
    default: op
  nerdspawn.spawn:
    description: Allow a player to teleport to spawn.
    default: op
  nerdspawn.setspawn:
    description: Allow a player to set the spawn location.
    default: op
  nerdspawn.reload:
    description: Allow a player to reload the configuration.
    default: op
  nerdspawn.list:
    description: Allow a player to list all the spawns.
    default: op

